coreutils-8.29-ls-abmon-width.patch: temporarily disable the check
... because it does not work today (May 29th) as reported upstream:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=31644

diff --git a/coreutils-8.29-ls-abmon-width.patch b/coreutils-8.29-ls-abmon-width.patch
--- a/coreutils-8.29-ls-abmon-width.patch
+++ b/coreutils-8.29-ls-abmon-width.patch
@@ -55,7 +55,7 @@ index e474047..a81266b 100755
      )
 +    n_dupes=$(echo "$months" | sort | uniq -d | wc -l)
      test "$n_widths" = "1" || { fail=1; break 2; }
-+    test "$n_dupes" = "0" || { fail=1; break 2; }
++    #test "$n_dupes" = "0" || { fail=1; break 2; }
    done
  done
  if test "$fail" = "1"; then
